// Code generated by hand for testing. DO NOT EDIT.
package tests

import (
	"github.com/golang/mock/gomock"
)

// MockUserRepository - мок для UserRepository
type MockUserRepository struct {
	ctrl           *gomock.Controller
	getBalanceResp []struct {
		result int
		err    error
	}
	updateBalanceResp []error
	getBalanceIdx     int
	updateBalanceIdx  int
}

func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	return &MockUserRepository{
		ctrl: ctrl,
		getBalanceResp: []struct {
			result int
			err    error
		}{},
		updateBalanceResp: []error{},
	}
}

func (m *MockUserRepository) GetBalance(userID string) (int, error) {
	if m.getBalanceIdx < len(m.getBalanceResp) {
		resp := m.getBalanceResp[m.getBalanceIdx]
		m.getBalanceIdx++
		return resp.result, resp.err
	}
	m.ctrl.T.Errorf("unexpected call to GetBalance(%q)", userID)
	return 0, nil
}

func (m *MockUserRepository) UpdateBalance(userID string, newBalance int) error {
	if m.updateBalanceIdx < len(m.updateBalanceResp) {
		err := m.updateBalanceResp[m.updateBalanceIdx]
		m.updateBalanceIdx++
		return err
	}
	m.ctrl.T.Errorf("unexpected call to UpdateBalance(%q, %d)", userID, newBalance)
	return nil
}

// Helper для установки expectations
func (m *MockUserRepository) ExpectGetBalance(userID string, result int, err error) {
	m.getBalanceResp = append(m.getBalanceResp, struct {
		result int
		err    error
	}{result, err})
}

func (m *MockUserRepository) ExpectUpdateBalance(userID string, balance int, err error) {
	m.updateBalanceResp = append(m.updateBalanceResp, err)
}

// MockLineRepository - мок для LineRepository
type MockLineRepository struct {
	ctrl                  *gomock.Controller
	getCountFreeSpinsResp []struct {
		result int
		err    error
	}
	updateCountFreeSpinsResp []error
	getCountFreeSpinsIdx     int
	updateCountFreeSpinsIdx  int
}

func NewMockLineRepository(ctrl *gomock.Controller) *MockLineRepository {
	return &MockLineRepository{
		ctrl: ctrl,
		getCountFreeSpinsResp: []struct {
			result int
			err    error
		}{},
		updateCountFreeSpinsResp: []error{},
	}
}

func (m *MockLineRepository) GetCountFreeSpins(userID string) (int, error) {
	if m.getCountFreeSpinsIdx < len(m.getCountFreeSpinsResp) {
		resp := m.getCountFreeSpinsResp[m.getCountFreeSpinsIdx]
		m.getCountFreeSpinsIdx++
		return resp.result, resp.err
	}
	m.ctrl.T.Errorf("unexpected call to GetCountFreeSpins(%q)", userID)
	return 0, nil
}

func (m *MockLineRepository) UpdateCountFreeSpins(userID string, newCount int) error {
	if m.updateCountFreeSpinsIdx < len(m.updateCountFreeSpinsResp) {
		err := m.updateCountFreeSpinsResp[m.updateCountFreeSpinsIdx]
		m.updateCountFreeSpinsIdx++
		return err
	}
	m.ctrl.T.Errorf("unexpected call to UpdateCountFreeSpins(%q, %d)", userID, newCount)
	return nil
}

// Helper для установки expectations
func (m *MockLineRepository) ExpectGetCountFreeSpins(userID string, result int, err error) {
	m.getCountFreeSpinsResp = append(m.getCountFreeSpinsResp, struct {
		result int
		err    error
	}{result, err})
}

func (m *MockLineRepository) ExpectUpdateCountFreeSpins(userID string, count int, err error) {
	m.updateCountFreeSpinsResp = append(m.updateCountFreeSpinsResp, err)
}

// MockLineConfig - мок для LineConfig
type MockLineConfig struct {
	ctrl                 *gomock.Controller
	symbolWeightsFn      func() map[string]int
	wildChanceFn         func() float64
	freeSpinsByScatterFn func() map[int]int
}

func NewMockLineConfig(ctrl *gomock.Controller) *MockLineConfig {
	return &MockLineConfig{
		ctrl: ctrl,
	}
}

func (m *MockLineConfig) SymbolWeights() map[string]int {
	if m.symbolWeightsFn != nil {
		return m.symbolWeightsFn()
	}
	return map[string]int{}
}

func (m *MockLineConfig) WildChance() float64 {
	if m.wildChanceFn != nil {
		return m.wildChanceFn()
	}
	return 0.0
}

func (m *MockLineConfig) FreeSpinsByScatter() map[int]int {
	if m.freeSpinsByScatterFn != nil {
		return m.freeSpinsByScatterFn()
	}
	return map[int]int{}
}

// Helper для установки expectations
func (m *MockLineConfig) ExpectSymbolWeights(result map[string]int) {
	m.symbolWeightsFn = func() map[string]int {
		return result
	}
}

func (m *MockLineConfig) ExpectWildChance(result float64) {
	m.wildChanceFn = func() float64 {
		return result
	}
}

func (m *MockLineConfig) ExpectFreeSpinsByScatter(result map[int]int) {
	m.freeSpinsByScatterFn = func() map[int]int {
		return result
	}
}
